// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quxodfekvvatzrddlpvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1eG9kZmVrdnZhdHpyZGRscHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDg2ODQsImV4cCI6MjA2MzkyNDY4NH0.k_K9HTIw3ie-3xi2JiEUelefb8DIaetE_uiLmubDjJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);